# Configuration file for custom user settings

if(CMAKE_HOST_WIN32)
    set(HOME_DIR $ENV{USERPROFILE})
else()
    set(HOME_DIR $ENV{HOME})
endif()

if(DEFINED RASC_EXE_PATH)
    message("Using RASC_EXE_PATH defined via CLI -D: ${RASC_EXE_PATH}")
elseif(DEFINED ENV{RASC_EXE_PATH})
    set(RASC_EXE_PATH $ENV{RASC_EXE_PATH})
    message("Using RASC_EXE_PATH defined in environment: ${RASC_EXE_PATH}")
else ()
    set(RASC_EXE_PATH "${HOME_DIR}/.renesas/platform/sc/ra/fsp_6.2.0/eclipse/rasc.exe")
    message("Using RASC_EXE_PATH generated by FSP application: ${RASC_EXE_PATH}")
endif()

# Renesas拡張機能のPythonを使用する設定
set(PYTHON_EXE "${HOME_DIR}/.renesas/platform/python310/python.exe")
